-- Oracle XE seed for the DB Tool dev environment (TASK 45).
-- Same customers / orders / order_items shape as the other engines, adapted to
-- Oracle: IDENTITY columns (12c+), VARCHAR2/NUMBER/TIMESTAMP types, is_active as
-- NUMBER(1). Run as the app user (dbtool) against XEPDB1.

CREATE TABLE customers (
  id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      VARCHAR2(255) NOT NULL,
  full_name  VARCHAR2(255) NOT NULL,
  is_active  NUMBER(1) DEFAULT 1 NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_customers_email UNIQUE (email)
);

CREATE TABLE orders (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id NUMBER NOT NULL,
  order_no    VARCHAR2(32) NOT NULL,
  status      VARCHAR2(20) DEFAULT 'pending' NOT NULL,
  total       NUMBER(10,2) DEFAULT 0 NOT NULL,
  notes       VARCHAR2(400),
  placed_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_orders_no UNIQUE (order_no),
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE TABLE order_items (
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    NUMBER NOT NULL,
  sku         VARCHAR2(64) NOT NULL,
  description VARCHAR2(255) NOT NULL,
  quantity    NUMBER DEFAULT 1 NOT NULL,
  unit_price  NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE VIEW active_customers AS
  SELECT id, email, full_name FROM customers WHERE is_active = 1;

INSERT INTO customers (email, full_name, is_active) VALUES ('ada.lovelace@example.com', 'Ada Lovelace', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('grace.hopper@example.com', 'Grace Hopper', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('alan.turing@example.com', 'Alan Turing', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('katherine.j@example.com', 'Katherine Johnson', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('linus.t@example.com', 'Linus Torvalds', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('margaret.h@example.com', 'Margaret Hamilton', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('donald.k@example.com', 'Donald Knuth', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('barbara.l@example.com', 'Barbara Liskov', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('tim.bl@example.com', 'Tim Berners-Lee', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('guido.vr@example.com', 'Guido van Rossum', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('dennis.r@example.com', 'Dennis Ritchie', 0);
INSERT INTO customers (email, full_name, is_active) VALUES ('ken.t@example.com', 'Ken Thompson', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('john.mccarthy@example.com', 'John McCarthy', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('edsger.d@example.com', 'Edsger Dijkstra', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('claude.s@example.com', 'Claude Shannon', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('john.vn@example.com', 'John von Neumann', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('adele.g@example.com', 'Adele Goldberg', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('frances.a@example.com', 'Frances Allen', 1);
INSERT INTO customers (email, full_name, is_active) VALUES ('niklaus.w@example.com', 'Niklaus Wirth', 0);
INSERT INTO customers (email, full_name, is_active) VALUES ('vint.c@example.com', 'Vint Cerf', 1);

INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (1,  'ORD-1001', 'paid',      129.98, 'Gift wrap requested');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (1,  'ORD-1002', 'shipped',    59.99, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (2,  'ORD-1003', 'paid',      249.50, 'Expedited shipping');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (3,  'ORD-1004', 'pending',    19.99, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (4,  'ORD-1005', 'shipped',   399.00, 'Signature on delivery');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (5,  'ORD-1006', 'cancelled',  89.90, 'Customer changed mind');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (6,  'ORD-1007', 'paid',      175.25, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (7,  'ORD-1008', 'refunded',   45.00, 'Damaged in transit');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (8,  'ORD-1009', 'paid',      612.75, 'Bulk order');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (9,  'ORD-1010', 'shipped',    32.49, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (10, 'ORD-1011', 'paid',      148.00, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (12, 'ORD-1012', 'pending',    74.99, 'Awaiting payment');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (14, 'ORD-1013', 'paid',      299.99, 'Corporate account');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (15, 'ORD-1014', 'shipped',    21.00, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (16, 'ORD-1015', 'paid',      450.00, 'Priority handling');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (17, 'ORD-1016', 'pending',    64.50, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (18, 'ORD-1017', 'paid',      110.10, NULL);
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (20, 'ORD-1018', 'shipped',   205.80, 'Fragile');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (4,  'ORD-1019', 'paid',       88.88, 'Repeat customer');
INSERT INTO orders (customer_id, order_no, status, total, notes) VALUES (6,  'ORD-1020', 'paid',      133.33, NULL);

INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (1, 'SKU-KB-01',  'Mechanical keyboard, brown switches', 1, 89.99);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (1, 'SKU-MP-01',  'Desk mouse pad, XL',                  2, 19.99);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (2, 'SKU-CB-USB', 'USB-C cable, 2m',                     1, 12.99);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (3, 'SKU-MON-27', '27-inch IPS monitor',                 1, 229.50);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (4, 'SKU-STK-01', 'Sticker pack, dev-themed',            1, 19.99);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (5, 'SKU-CHR-01', 'Ergonomic office chair',              1, 379.00);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (5, 'SKU-CB-USB', 'USB-C cable, 2m',                     1, 12.99);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (7, 'SKU-KB-02',  'Mechanical keyboard, blue switches',  1, 95.25);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (8, 'SKU-MUG-01', 'Coffee mug, 350ml',                   1, 25.01);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (9, 'SKU-DSK-01', 'Standing desk, 140cm',                1, 549.75);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (11,'SKU-WCM-01', 'Webcam, 1080p',                       1, 68.00);
INSERT INTO order_items (order_id, sku, description, quantity, unit_price) VALUES (13,'SKU-MON-27', '27-inch IPS monitor',                 1, 229.99);

COMMIT;
